### ISSUE TITLE
History record to be available on entity hook for Insert operation

### ISSUE THREAD

**Issue by joemocquant** [flume/enthistory#65]
I am looking to have a global hook that retrieves the history id of the current entity operation the global hook is on.

It works for update/delete but not insert (getting this error `[entity]_history not found` with `entity` the name of the entity).

Looking at enthistory code, I believe the issue is because in `historyHookCreate`, `next.Mutate()` is called before `mutation.CreateHistoryFromCreate()` (this is not the case for [historyHookUpdate](https://github.com/flume/enthistory/blob/eb5376428c6a88b2251f718bddd313267d4bf30d/hook.go#L84-L100) and [historyHookDelete](https://github.com/flume/enthistory/blob/eb5376428c6a88b2251f718bddd313267d4bf30d/hook.go#L102-L118)):

https://github.com/flume/enthistory/blob/eb5376428c6a88b2251f718bddd313267d4bf30d/hook.go#L61-L82

- Could it be possible to have Create following the same ordering as in Update and Delete (or is there any particular reason for the ordering being different, like some kind of egg and chicken issue)?

- if not, what would be the best generic approach/solution to automatically execute code synchronically (avoiding consistency or other similar issues) that captures the history record for any entity operation?

Thanks in advance!

**Comment by frisbm** [comment]
Hi again @joemocquant

The `historyHookCreate` does need to have a different control flow than the update and delete hooks because of the database needing to auto-increment and set IDs on the data, just as you suspected (chicken vs. the egg), there's not really a way to change it unfortunately.

But in your case I imagine you have a global hook that is set to run on any operation, but if you made two hooks, one that ran on all of the update and delete operations and one that ran on the create operations, you could control where `next.Mutate(ctx, m)` was being called from there. So if you want enthistory/ent hooks to run either before or after your logic you could control that from within each hook separately, similar to what we had to do in the snippet you shared

**Comment by joemocquant** [comment]
@frisbm The first part makes sense, I did not think about the ID issue as I am not using auto-increment.

Regarding the second part, I am calling `next.Mutate` before the hook core logic (which retrieve the history record), and this does not work for `ent.OpCreate`. So I am not sure if I understand correctly your suggestion.

Here is how I ideally would like this to work:
```
func CustomHook() ent.Hook {
	return func(next ent.Mutator) ent.Mutator {
		return ent.MutateFunc(
			func(ctx context.Context, m ent.Mutation) (ent.Value, error) {
				value, err := next.Mutate(ctx, m)
				if err != nil {
					return nil, err
				}

				if m.Op().Is(ent.OpCreate) {
					return value, nil 
                                         // to avoid panic() 
                                         // as retrieving history does not work for ent.OpCreate
				}

                                 // Hook core logic including retrieving history record

				return value, nil
			},
  		)
	}
}
```

(Also, `WithHistory()` is called before registering to the CustomHook)

Were you suggesting a different solution?

**Comment by joemocquant** [comment]
I am thinking one solution is to actually create the hook on [Entity]History. So that should work for any kind of operation.
